// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/segment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Document represents an indexed file
type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	TokenCount    uint32                 `protobuf:"varint,3,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_proto_segment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_proto_segment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_proto_segment_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Document) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Document) GetTokenCount() uint32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

// Posting represents a term occurrence in a document
type Posting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         uint32                 `protobuf:"varint,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Freq          uint32                 `protobuf:"varint,2,opt,name=freq,proto3" json:"freq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Posting) Reset() {
	*x = Posting{}
	mi := &file_proto_segment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Posting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Posting) ProtoMessage() {}

func (x *Posting) ProtoReflect() protoreflect.Message {
	mi := &file_proto_segment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Posting.ProtoReflect.Descriptor instead.
func (*Posting) Descriptor() ([]byte, []int) {
	return file_proto_segment_proto_rawDescGZIP(), []int{1}
}

func (x *Posting) GetDocId() uint32 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *Posting) GetFreq() uint32 {
	if x != nil {
		return x.Freq
	}
	return 0
}

// PostingList holds all postings for a single term
type PostingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Postings      []*Posting             `protobuf:"bytes,1,rep,name=postings,proto3" json:"postings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostingList) Reset() {
	*x = PostingList{}
	mi := &file_proto_segment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostingList) ProtoMessage() {}

func (x *PostingList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_segment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostingList.ProtoReflect.Descriptor instead.
func (*PostingList) Descriptor() ([]byte, []int) {
	return file_proto_segment_proto_rawDescGZIP(), []int{2}
}

func (x *PostingList) GetPostings() []*Posting {
	if x != nil {
		return x.Postings
	}
	return nil
}

// Segment is the main index structure
type Segment struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Docs          []*Document             `protobuf:"bytes,1,rep,name=docs,proto3" json:"docs,omitempty"`
	InvertedIndex map[string]*PostingList `protobuf:"bytes,2,rep,name=inverted_index,json=invertedIndex,proto3" json:"inverted_index,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TotalDocs     uint32                  `protobuf:"varint,3,opt,name=total_docs,json=totalDocs,proto3" json:"total_docs,omitempty"`
	TotalTokens   uint32                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	AvgDocLen     uint32                  `protobuf:"varint,5,opt,name=avg_doc_len,json=avgDocLen,proto3" json:"avg_doc_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_proto_segment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_segment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_proto_segment_proto_rawDescGZIP(), []int{3}
}

func (x *Segment) GetDocs() []*Document {
	if x != nil {
		return x.Docs
	}
	return nil
}

func (x *Segment) GetInvertedIndex() map[string]*PostingList {
	if x != nil {
		return x.InvertedIndex
	}
	return nil
}

func (x *Segment) GetTotalDocs() uint32 {
	if x != nil {
		return x.TotalDocs
	}
	return 0
}

func (x *Segment) GetTotalTokens() uint32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *Segment) GetAvgDocLen() uint32 {
	if x != nil {
		return x.AvgDocLen
	}
	return 0
}

var File_proto_segment_proto protoreflect.FileDescriptor

const file_proto_segment_proto_rawDesc = "" +
	"\n" +
	"\x13proto/segment.proto\x12\x05mneme\"O\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1f\n" +
	"\vtoken_count\x18\x03 \x01(\rR\n" +
	"tokenCount\"4\n" +
	"\aPosting\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\rR\x05docId\x12\x12\n" +
	"\x04freq\x18\x02 \x01(\rR\x04freq\"9\n" +
	"\vPostingList\x12*\n" +
	"\bpostings\x18\x01 \x03(\v2\x0e.mneme.PostingR\bpostings\"\xb0\x02\n" +
	"\aSegment\x12#\n" +
	"\x04docs\x18\x01 \x03(\v2\x0f.mneme.DocumentR\x04docs\x12H\n" +
	"\x0einverted_index\x18\x02 \x03(\v2!.mneme.Segment.InvertedIndexEntryR\rinvertedIndex\x12\x1d\n" +
	"\n" +
	"total_docs\x18\x03 \x01(\rR\ttotalDocs\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\rR\vtotalTokens\x12\x1e\n" +
	"\vavg_doc_len\x18\x05 \x01(\rR\tavgDocLen\x1aT\n" +
	"\x12InvertedIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.mneme.PostingListR\x05value:\x028\x01B\x18Z\x16mneme/internal/core/pbb\x06proto3"

var (
	file_proto_segment_proto_rawDescOnce sync.Once
	file_proto_segment_proto_rawDescData []byte
)

func file_proto_segment_proto_rawDescGZIP() []byte {
	file_proto_segment_proto_rawDescOnce.Do(func() {
		file_proto_segment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_segment_proto_rawDesc), len(file_proto_segment_proto_rawDesc)))
	})
	return file_proto_segment_proto_rawDescData
}

var file_proto_segment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_segment_proto_goTypes = []any{
	(*Document)(nil),    // 0: mneme.Document
	(*Posting)(nil),     // 1: mneme.Posting
	(*PostingList)(nil), // 2: mneme.PostingList
	(*Segment)(nil),     // 3: mneme.Segment
	nil,                 // 4: mneme.Segment.InvertedIndexEntry
}
var file_proto_segment_proto_depIdxs = []int32{
	1, // 0: mneme.PostingList.postings:type_name -> mneme.Posting
	0, // 1: mneme.Segment.docs:type_name -> mneme.Document
	4, // 2: mneme.Segment.inverted_index:type_name -> mneme.Segment.InvertedIndexEntry
	2, // 3: mneme.Segment.InvertedIndexEntry.value:type_name -> mneme.PostingList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_segment_proto_init() }
func file_proto_segment_proto_init() {
	if File_proto_segment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_segment_proto_rawDesc), len(file_proto_segment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_segment_proto_goTypes,
		DependencyIndexes: file_proto_segment_proto_depIdxs,
		MessageInfos:      file_proto_segment_proto_msgTypes,
	}.Build()
	File_proto_segment_proto = out.File
	file_proto_segment_proto_goTypes = nil
	file_proto_segment_proto_depIdxs = nil
}
